language: python
sudo: false

env:
  global:
    - secure: "mCqfVOASCDiS6eD5douIObutOcSIC/kawrV8HDeC/fJmPZSctartcUkjhYYLwerzKfbp9U2Uddwwrabn225NdDaRNkpEBYF4l2GhmRPIx6ia1IPyznsJkQfHcXU9JBf90pVTSzAJgGY72clcfq/3o4yqMwV+5/CBCBf3FUWvkUAl8Pqo+ttZrWZQy5CmHo/CqOadNW/+ChdU+DEyFVTy3bMrRWdPXp9kT4/M3Zv8+3yiqTQvGT0zXGGv9tNjG5q+tt+fhBkwNnmbqk+dWX4dwi+VQZpBdHdDED+2igXGR8wLWHV2gSCXbac/kt+Aw5Hi1wvTjqtofsp6B9A3IXNKgRoqwXnEoA9qg88q8mUdT1AdOLghYBS/cVsZe2tizp5R82pHzZ0Zcd1IgFrCZPWjYH27oTOo863x0BRH+UxjwbeoVoYRtnCgorkFDFRPk8062J8Pvppa+38M/QCCTMLHqaM+yJoUpanA3U3TzIA81lZFbKqWBF4LDHsEy1bCoZdcETs0TV1uMrB7qsF57Cfce7LwlkzP6BLXOn+xEEbAfcDiEbBTW9wxwDE3DaXwVv5DyeQzXoLR9Tt4Pn3AOjdemhFL30OfM9CGBJ1Yg2mFh0fD4ygTCOA8QjDMoWIGpzTL8KAc8m52IbaFYL+DKVOluZwetXzC9WdcGb+fcqQCT70="

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/matplotlib

python:
  - 3.5
  - 3.6
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/mc
  - export PATH=~/mc/bin:$PATH
  - conda update conda --yes
  - conda config --add channels conda-forge


install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda create --yes -n testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --yes --file requirements/build.txt
  - conda install pip
  - pip install -r requirements/pip.txt
  - pip install .

script:
  - set -e
  - conda install --yes --file requirements/run.txt
  - conda install --yes --file requirements/test.txt
  - pip install codecov pytest-env
  - coverage run run_tests.py
  - coverage report -m
  - codecov
  - image_to_iq -- --help
  - flake8 xpdtools
  - conda install --yes --file requirements/docs.txt
  - pip install git+git://github.com/drdoctr/doctr.git
  - cd docs
  - make html
  - cd ..
  - doctr deploy . --built-docs ./docs/_build/html;
